### ISSUE TITLE
支持查看抽奖信息并一键转发

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#181]

**Comment by WindowsMEMZ** [comment]
网页上没有这个，喵哩喵哩全部走的网页API，况且app的这个API也没找到，没什么作用

**Comment by Linecom-lik** [comment]
> 网页上没有这个，喵哩喵哩全部走的网页API，况且app的这个API也没找到，没什么作用

隔壁安卓腕上哔哩第一版就已经实现了（（

**Comment by Linecom-lik** [comment]
查看抽奖信息一个API
转发一个API
是分开的

**Comment by Linecom-lik** [comment]
![image](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/0c831d73-76e5-47d7-b77d-9c28e8565479)
