### ISSUE TITLE
支持视频播放时快捷切换音频输出

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#194]

**Comment by WindowsMEMZ** [comment]
没看懂你这个什么意思

**Comment by Linecom-lik** [comment]
> 没看懂你这个什么意思
![incoming-EF08F3CF-E779-4620-AF51-2662BB70D466](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/11f86e37-1cbf-4705-9960-4808bbe6f75a)
![incoming-68C1D1FD-7250-40ED-9FF1-4B9344F962E3](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/edd080fb-0710-40c7-abb6-970836b9a2ad)

**Comment by Linecom-lik** [comment]
播放视频的时候切换蓝牙输出（

**Comment by WindowsMEMZ** [comment]
视频页有视频，没办法放toolbar，放右边菜单的话，用户不如直接打开控制中心来切换
