### ISSUE TITLE
iOS:显示头图

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#199]

**Comment by WindowsMEMZ** [comment]
iOS为Alpha版本，目前不接受反馈

**Comment by Linecom-lik** [comment]
现在不是了

**Comment by WindowsMEMZ** [comment]
@Linecom-lik 什么头图？

**Comment by Linecom-lik** [comment]
> @Linecom-lik 什么头图？

就是个人资料上面的背景
![IMG_1051](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/cd3d9012-991f-43f1-bb40-8556b9c0f280)

**Comment by Linecom-lik** [comment]
注意移动端和网页端的头图是分开的（
