### ISSUE TITLE
手机号登录的国际冠码部分改为选择

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#219]
给出指定冠码以及对应国家，让用户选择

**Comment by Linecom-lik** [comment]
本来决定我做了，不过sm的Xcode天天未响应，所以开issue算了。（再加上我对swift不熟）

**Comment by ThreeManager785** [comment]
这不巧了嘛，最近正好打算把LoginView改一下（

**Comment by ThreeManager785** [comment]
我计划改

**Comment by ThreeManager785** [comment]
太地狱了

**Comment by ThreeManager785** [comment]
这个东西好麻烦，一个一个配对要配对195个或者更多，让ChatGPT或者Gemini俩人各输出的两个数组长度都不匹配。我开学了再做。发自我的 iPad ProOn Feb 22, 2024, at 2:11 AM, Weidong Cheng ***@***.***> wrote:﻿
Assigned #219 to @ThreeManager785.
