### ISSUE TITLE
WatchOS 10.0以上hideDigitalTime里的方法无效

### ISSUE THREAD

**Issue by caichunjian520** [Darock-Studio/Darock-Bili#23]
不能隐藏时间？

**Comment by WindowsMEMZ** [comment]
因`hideDigitalTime`为私有方法，Apple 似乎在watchOS 10更改了此方法，我们正在寻找解决方案。

**Comment by caichunjian520** [comment]
明白的，app store上的clockology在WatchOS 10以上也是可以隐藏时间的，所以这个私有方法找到应该的确是可以做到。

**Comment by WindowsMEMZ** [comment]
在 watchOS 10 上目前无公开的私有 API 可以隐藏右上角时间。我了解到可以在 `Picker` 空间上进行 `overlay` 来达到此效果，但这会导致布局叫困难。我们会在考虑后决定是否使用此功能。
