### ISSUE TITLE
屏幕使用时间 横轴显示错误

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#251]
![IMG_1056](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/8c271da2-3bb0-463c-a40d-50fb7886d1bd)

**Comment by WindowsMEMZ** [comment]
没什么用，不准备弄这个板块了，之后会移除iOS的（毕竟有了），watchOS会更改显示方式。
