### ISSUE TITLE
屏幕顶部「喵哩喵哩」在灵动岛机型上会有部分露出

### ISSUE THREAD

**Issue by ThreeManager785** [Darock-Studio/Darock-Bili#252]
<img width="559" alt="Screenshot 2024-02-20 at 12 28 24 PM" src="https://github.com/Darock-Studio/Darock-Bili/assets/113956386/eedf26dd-8916-4188-be5a-814bd613112f">
<img width="559" alt="Screenshot 2024-02-20 at 12 28 37 PM" src="https://github.com/Darock-Studio/Darock-Bili/assets/113956386/305af6cf-c2fe-4c82-8cd6-5f4b3a921bbd">
如图

**Comment by ThreeManager785** [comment]
emmmm图片没出来

**Comment by ThreeManager785** [comment]
啊，还是能看的

**Comment by WindowsMEMZ** [comment]
已修复，将在下一个pr中提交
