### ISSUE TITLE
希望添加watchOS端喵哩喵哩稍后再看页面的左滑删除的功能。

### ISSUE THREAD

**Issue by ZJH58** [Darock-Studio/Darock-Bili#254]
希望添加watchOS端喵哩喵哩稍后再看左滑删除的功能。

**Comment by Linecom-lik** [comment]
@WindowsMEMZ 你不觉得和 #133 #121 重复吗（（

**Comment by Linecom-lik** [comment]
> 仔细寻找后watch端并未找到“管理”页面，watchOS为10.3.1，机型是Apple Watch Ultra 2。

我说的是issue重复，并不是已有功能

**Comment by WindowsMEMZ** [comment]
更新已合并到main
