### ISSUE TITLE
登录后动态界面文字问题

### ISSUE THREAD

**Issue by zihanwan** [Darock-Studio/Darock-Bili#258]
ios 端在浏览动态时有时会有文字消失的情况

**Comment by WindowsMEMZ** [comment]
不是文字消失，应该是动态类型不支持，导致没有可显示的内容。今后会添加更多动态类型支持

**Comment by Linecom-lik** [comment]
> ~不是文字消失，应该是动态类型不支持，导致没有可显示的内容。今后会添加更多动态类型支持~
> 
> 已确认问题，正在修复

🦁写的好代码（
下次他交pr你得多检查 @WindowsMEMZ

**Comment by WindowsMEMZ** [comment]
已revert
