### ISSUE TITLE
视频列表会重复获取视频

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#259]
![81810BBE-E824-458E-BEA3-A4B7743B1D4A_4_5005_c](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/40938e7c-9ff1-4bca-9175-697d74a8d009)
![350041AB-1256-4358-A632-DAAA3C8A4D84_4_5005_c](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/44b9fe7b-a293-4f76-9f4c-5208c6a2e4d0)

**Comment by WindowsMEMZ** [comment]
已修复，将在下一个pr中提交
