### ISSUE TITLE
搜索时出现csrf校验失败

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#260]
![7BE43679-A61F-4A63-B0BC-957355F86D3E_4_5005_c](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/0a7ec39f-240a-485e-8c92-998dd844c9db)
其他关键词是好的，直到我昨晚搜了个“药娘”（（（

**Comment by WindowsMEMZ** [comment]
这我感觉和关键字没什么关系，既然它有可能校验csrf那我把搜索API之后统一多传入一个csrf就行

**Comment by Linecom-lik** [comment]
> 这我感觉和关键字没什么关系，既然它有可能校验csrf那我把搜索API之后统一多传入一个csrf就行

但是我只有搜这个关键字会爆csrf

**Comment by WindowsMEMZ** [comment]
我发现我是传了csrf的，这下不好搞了，而且我这搜这个就没问题
