### ISSUE TITLE
WatchOS登录后闪退

### ISSUE THREAD

**Issue by noxsk** [Darock-Studio/Darock-Bili#283]
系统版本：Watch OS 10.4 beta  4（此前几个beta也是同样问题）
现象：在Build 398之后，可以正常进入加载，一旦登录后就闪退无法再次进入

PS：由于是beta系统，可能是系统原因，之前因为是beta我就等了两次更新但是没有解决问题，beta 4的更新日志也没有已知问题。

**Comment by Linecom-lik** [comment]
最新正式版watchOS10.3.1使用Build860功能正常，喵哩喵哩不对Beta版系统支持。
