### ISSUE TITLE
动态界面显示缩略图

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#314]
![IMG_1339](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/c0b6ae3f-615e-4778-b6d5-7e0f12b3686d)

![IMG_1338](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/1ac7e1ea-2e8f-40cc-92f7-476545f63fbd)
看这布局吧、为什么要在动态预览界面放原图呢（
看个动态给我看懵圈了（（

**Comment by WindowsMEMZ** [comment]
[rdar://2049673592](https://darock.top/internal/radar/go?id=2049673592)
