### ISSUE TITLE
testflight名额已满

### ISSUE THREAD

**Issue by whatIsUsrname** [Darock-Studio/Darock-Bili#327]
![IMG_2835](https://github.com/Darock-Studio/Darock-Bili/assets/110437974/57fa8c58-a282-4b5d-b1ac-0ce84806af71)
第一次在GitHub上提issue，如有冒犯/麻烦非常抱歉～开发者可不可以再开一个，这个满了，谢谢

**Comment by WindowsMEMZ** [comment]
测试链接已更新为[这个](https://testflight.apple.com/join/skaCe2L2)，我们将在稍后更新Readme文档
