### ISSUE TITLE
安装名额满了

### ISSUE THREAD

**Issue by Nlmiki** [Darock-Studio/Darock-Bili#328]
如有打扰还请原谅，能不能再开一个，用#327里面给的testflight提示人满了
![Uploading IMG_3129.png…]()

**Comment by WindowsMEMZ** [comment]
我们正在联系 Apple 支持，还请耐心等待。

![image](https://github.com/Darock-Studio/Darock-Bili/assets/45706356/d728fb7d-6550-4bbc-82eb-3d64c13f4218)

**Comment by xunmod** [comment]
我寻思发行版可以带个ipa什么，然后我们可用用altstore之类的东西侧载一下

**Comment by FengzihangCode** [comment]
IPA可以侧载到Apple Watch上面嘛？ 没有见到过有项目侧载到了Apple Watch上 不知道技术上是否可行 但是是个很有意思的主意 想试试（


发自我的 Apple Watch

**Comment by xunmod** [comment]
> IPA可以侧载到Apple Watch上面嘛？ 没有见到过有项目侧载到了Apple Watch上 不知道技术上是否可行 但是是个很有意思的主意 想试试（ 发自我的 Apple Watch

sorry啦。我以为楼主是在说ios端的

**Comment by FengzihangCode** [comment]
自行编译项目还是最方便的替代解决方法 但是前提是要有Mac 剩余的人除了TestFlight应该没有什么安装到Apple Watch的方法了


发自我的 Apple Watch
