### ISSUE TITLE
动态页面无法显示对应动态的图片

### ISSUE THREAD

**Issue by shiruifan** [Darock-Studio/Darock-Bili#334]
![F4F60EA4-61A2-4CCA-98B0-CA94651A6EDF](https://github.com/Darock-Studio/Darock-Bili/assets/69615623/777ccad6-9b7d-4888-8e02-a19288531289)
![CFB2DD4D-1EFB-437C-80B8-78FD93BFDE87](https://github.com/Darock-Studio/Darock-Bili/assets/69615623/f2ad6470-435e-4815-916f-4b4a75a63292)
![EF5CDA9F-1533-4BD3-A2B2-50A3ADB5E628](https://github.com/Darock-Studio/Darock-Bili/assets/69615623/a325ffa2-49d5-480f-a0c2-86b8213c6f59)
![17E0F119-519F-4178-B751-8976CFEB5D7E](https://github.com/Darock-Studio/Darock-Bili/assets/69615623/e0c7e90e-1da9-427d-a086-c62fc4810082)
如图所示，两种图片方式均无法显示

**Comment by WindowsMEMZ** [comment]
[rdar://2049673590](https://darock.top/internal/radar/go?id=2049673590)
