### ISSUE TITLE
软件版本：1.1.4(1069)，系统版本：10.4（21T216）

### ISSUE THREAD

**Issue by chinachinese1** [Darock-Studio/Darock-Bili#355]
在打开储存空间与关于时，出现**闪退**的情况
在下载一bv多视频类型时**无法**离线缓存，且在下载完视频后会占用内存**无法删除**，例如"BV1Nr42137s3"

**Comment by WindowsMEMZ** [comment]
[rdar://2049673550](https://darock.top/internal/radar/go?id=2049673550)
