### ISSUE TITLE
没下载完时下载下一个视频,会下多一个

### ISSUE THREAD

**Issue by Jacky-whq** [Darock-Studio/Darock-Bili#359]
版本v2.8.0(1138)
OS版本10.4 (21T216)
当在没下载完时下载下一个视频，会下载多一个视频; 删除时会闪退
https://github.com/Darock-Studio/Darock-Bili/assets/118589838/569fa25a-666b-48bc-8edc-fa34d6f3b560

**Comment by noxsk** [comment]
经常复现，如果用流量就得一个一个下否则流量飞起😆😆
