### ISSUE TITLE
评论显示图片

### ISSUE THREAD

**Issue by FengZi-lv** [Darock-Studio/Darock-Bili#363]
部分视频评论可能带有图片，建议支持查看

**Comment by FengZi-lv** [comment]
类似于这种

![image](https://github.com/Darock-Studio/Darock-Bili/assets/59948673/1ecf483f-a084-49c9-a020-abfcca9c861a)

**Comment by WindowsMEMZ** [comment]
已在 Radar 中跟踪：[rdar://2049673589](https://darock.top/internal/radar/go?id=2049673589)
