### ISSUE TITLE
请求最低系统版本降级

### ISSUE THREAD

**Issue by diyanqi** [Darock-Studio/Darock-Bili#390]
老手机只有 `iOS15.8` ，而喵哩喵哩的最低版本要求是17.0，这使得我无法安装（watchOS是最新版本）。

请问能否将最低系统版本降到 15.x ，感激不尽😭

![image](https://github.com/user-attachments/assets/ca84e997-b3a4-4649-a1f8-1eef00b36977)

**Comment by WindowsMEMZ** [comment]
喵哩喵哩提供对于iOS 16的兼容通道，但从未支持iOS 15，你可以选择自己clone一份代码尝试为你的硬件提供兼容性
