### ISSUE TITLE
一些些问题反馈

### ISSUE THREAD

**Issue by WMR-Ram** [Darock-Studio/Darock-Bili#92]
下载视频的时候只能停留在下载页面，不能后台下载
看视频的时候会自动翻转视频180度
看视频的时候不能调整音量
全屏视频后不能调整视频位置

**Comment by WindowsMEMZ** [comment]
* 后台下载已在计划中
* 当前正在为更新播放器工作，之后播放器会大改，更新许多功能，包括提到的这些功能：
    > 看视频的时候会自动翻转视频180度
看视频的时候不能调整音量
全屏视频后不能调整视频位置

**Comment by WindowsMEMZ** [comment]
下载功能将于 #94 更新, 本 Issue 已处理完毕.
