### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by Linecom-lik** [Darock-Studio/Darock-Bili#98]
> 简洁一点，全都放到最上面
## 初始提交
- [ ] #113
- [x] ~~首页推荐增加下拉刷新~~ (wontfix)
- [x] 增加删除历史记录功能
- [ ] #114
- [x] 屏幕使用时间开关
- [x] 离线缓存增加取消任务与断点续传
- [x] 视频页离线缓存开始后进入任务列表而不是关闭窗口
- [x] 大会员标识换成贴图

## 从 #46 迁移的建议:
* [x]  头像下显示用户大会员角标（如果有）
* [ ] #115
* [ ] #116

## 2月2日新增

- [ ] #117
- [ ] #118
- [ ] #119
- [ ] #120
- [ ] #121
- [ ] #122
- [x] 支持登录多个账号
- [ ] #123
- [ ] #124
- [ ] #127
- [x] 支持显示评论中的表情包

## 2月5日新增

- [ ] #125
- [ ] #126
- [x] 整合哔哩哔哩漫画（或者单独出app）
- [ ] #128
- [ ] #129
- [x] 显示用户头像框（
- [x] 查看用户B币余额
- [x] 支持给up主充电
- [ ] 支持将视频/专栏投稿、用户直播动态单列
- [ ] 支持查看Bilibili话题
- [ ] 支持Bilibili音乐相关功能
- [x] 支持搜索直播

## 2月9日新增 - 除夕快乐

- [ ] #130
- [ ] #131
- [ ] #132
- [ ] #133
- [ ] #134
- [ ] #135
- [x] 用户页展示学校信息
- [ ] #136
- [ ] #137
- [ ] #138
- [ ] #139
- [ ] #140
- [ ] #141
- [ ] #142
- [ ] #143
- [ ] #144
- [x] 支持发表文字动态
- [ ] #145
- [ ] #146
- [ ] #147
- [ ] #148
- [ ] #149
- [ ] #150
- [ ] #151
- [ ] #152
- [ ] #153
- [x] 支持一键取关注销用户
- [ ] 支持查看bilibili帮助
- [ ] #154
- [x] 增加定时关闭功能
- [ ] #155
- [ ] 支持清除应用数据缓存（如果有生成的话）
- [x] 支持查看用户实名（不太可能
- [x] 支持视频镜像翻转
- [ ] #156
- [ ] #157
- [ ] #158
- [ ] #159
- [ ] #160
- [x] 支持将用户设为悄悄关注（B站官方这功能已经没了
- [x] 支持预约视频

**Comment by WindowsMEMZ** [comment]
## 从 #46 迁移的建议:
- [ ] 头像下显示用户大会员角标（如果有）
- [ ] 增加用户动态显示
- [ ] 增加全站热门板块

**Comment by WindowsMEMZ** [comment]
> - [x] ~~首页推荐增加下拉刷新~~ (wontfix)

早就有这个想法了，但现在 watchOS 实在没办法实现此功能(微信似乎实现了，但那肯定是用 `UIKit` 那古老框架实现的，要是给这个做 SwiftUI 调用 UIKit，代码会成为屎山中的屎山)，因此不会做此功能。

但之后会考虑给所有列表做滑动到最底部后自动加载。

**Comment by Linecom-lik** [comment]
那可以用长按菜单吗？那个不会也是uikit的吧发送自澪的Apple Watch Series 8在 2024年1月30日，22:06，Mark Chan ***@***.***> 写道：


 首页推荐增加下拉刷新 (wontfix)


早就有这个想法了，但现在 watchOS 实在没办法实现此功能(微信似乎实现了，但那肯定是用 UIKit 那古老框架实现的，要是给这个做 SwiftUI 调用 UIKit，代码会成为屎山中的屎山)，因此不会做此功能。
但之后会考虑给所有列表做滑动到最底部后自动加载。

**Comment by WindowsMEMZ** [comment]
> 那可以用长按菜单吗？那个不会也是uikit的吧

没见过什么长按菜单, 为什么加载要用长按菜单啊

**Comment by WindowsMEMZ** [comment]
> 增加删除历史记录功能

已 Merge 到`main`

**Comment by WindowsMEMZ** [comment]
> 屏幕使用时间开关

已 Merge 到`main`

**Comment by WindowsMEMZ** [comment]
> 离线缓存增加取消任务~~与断点续传~~(先前版本已支持)
 > 视频页离线缓存开始后(允许)进入任务列表而不是关闭窗口

已 Merge 到`main`

**Comment by WindowsMEMZ** [comment]
> ~~头像下显示用户大会员角标（如果有）~~

not planned

**Comment by Linecom-lik** [comment]
## 2月2日新增

- [ ] 支持一键三连
- [ ] 支持识别动态中的链接并用Safari打开
- [ ] 动态图片/视频封面支持保存
- [ ] 新增点踩功能
- [ ] 支持管理收藏/稍后再看
- [ ] 支持创建/删除收藏夹
- [ ] 支持登录多个账号

**Comment by Linecom-lik** [comment]
还有能不能把个人中心改成这样：
![IMG_0809](https://github.com/Darock-Studio/Darock-Bili/assets/69106177/cd231e38-c058-4b19-bd1c-bfb9208133ff)
（大概布局）感觉这样更紧凑（

**Comment by WindowsMEMZ** [comment]
> ~~支持一键三连~~

SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个

> ~~支持显示评论中的表情包~~

过于复杂, 没实力

> 动态图片/视频封面支持保存

保存到哪里?

**Comment by WindowsMEMZ** [comment]
> 还有能不能把个人中心改成这样： ![IMG_0809](https://private-user-images.githubusercontent.com/69106177/301691376-cd231e38-c058-4b19-bd1c-bfb9208133ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzY3NTIsIm5iZiI6MTcwNjg3NjQ1MiwicGF0aCI6Ii82OTEwNjE3Ny8zMDE2OTEzNzYtY2QyMzFlMzgtYzA1OC00YjE5LWJkMWMtYmZiOTIwODEzM2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDEyMjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NWNjYWIxZmJkMGFkMTllM2I5YjM1YjVhZTQ2MjU5YzcxOGYwZDE4NmI1MWQxMjhiZmY1ZTZkY2UwYmFkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZlFtwnPa_fwtIbKSmmymMtMW3II1ib5RWAc1ivXB2y8) （大概布局）感觉这样更紧凑（

感觉不太好

**Comment by Linecom-lik** [comment]
> > ~支持一键三连~
> 
> SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> 
> > ~支持显示评论中的表情包~
> 
> 过于复杂, 没实力
> 
> > 动态图片/视频封面支持保存
> 
> 保存到哪里?

可以在我的单独整个入口（

**Comment by WindowsMEMZ** [comment]
> > > ~支持一键三连~
> > 
> > 
> > SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> > > ~支持显示评论中的表情包~
> > 
> > 
> > 过于复杂, 没实力
> > > 动态图片/视频封面支持保存
> > 
> > 
> > 保存到哪里?
> 
> 可以在我的单独整个入口（

这算了, 没必要, 支持跳转到暗礁图片倒是可以[doge]

**Comment by Linecom-lik** [comment]
> > > > ~支持一键三连~
> > > 
> > > 
> > > SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> > > > ~支持显示评论中的表情包~
> > > 
> > > 
> > > 过于复杂, 没实力
> > > > 动态图片/视频封面支持保存
> > > 
> > > 
> > > 保存到哪里?
> > 
> > 
> > 可以在我的单独整个入口（
> 
> 这算了, 没必要, 支持跳转到暗礁图片倒是可以[doge]

所以转到暗礁图片能整吗？

**Comment by WindowsMEMZ** [comment]
> > > > > ~支持一键三连~
> > > > 
> > > > 
> > > > SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> > > > > ~支持显示评论中的表情包~
> > > > 
> > > > 
> > > > 过于复杂, 没实力
> > > > > 动态图片/视频封面支持保存
> > > > 
> > > > 
> > > > 保存到哪里?
> > > 
> > > 
> > > 可以在我的单独整个入口（
> > 
> > 
> > 这算了, 没必要, 支持跳转到暗礁图片倒是可以[doge]
> 
> 所以转到暗礁图片能整吗？

当然可以, 暗礁图片可是付费 App(((

**Comment by Linecom-lik** [comment]
# 2月5日新增

- [ ] 增加动态评论与互动
- [ ] 增加分区
- [ ] 整合哔哩哔哩漫画（或者单独出app）
- [ ] 增加消息中心
- [ ] 增加投稿管理
- [ ] 显示用户头像框（
- [ ] 查看用户B币余额
- [ ] 支持给up主充电
- [ ] 支持将视频/专栏投稿、用户直播动态单列
- [ ] 支持查看Bilibili话题
- [ ] 支持Bilibili音乐相关功能
- [ ] 支持搜索直播

**Comment by WindowsMEMZ** [comment]
> ~~整合哔哩哔哩漫画（或者单独出app）~~ (not planned)
> ~~显示用户头像框（~~ watch屏幕大小不适合这些东西
> ~~查看用户B币余额~~
> ~~支持给up主充电~~

⬆️ 不做支付相关功能
> 支持搜索直播

早就支持了

**Comment by ThreeManager785** [comment]
> > ~支持一键三连~
> 
> SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> 
> > ~支持显示评论中的表情包~
> 
> 过于复杂, 没实力
> 
> > 动态图片/视频封面支持保存
> 
> 保存到哪里?

.onLongPressGesture

**Comment by WindowsMEMZ** [comment]
> > > ~支持一键三连~
> > 
> > 
> > SwiftUI 没有 `onPressDown` Event, 用户反馈不好做, 不考虑这个
> > > ~支持显示评论中的表情包~
> > 
> > 
> > 过于复杂, 没实力
> > > 动态图片/视频封面支持保存
> > 
> > 
> > 保存到哪里?
> 
> .onLongPressGesture

这样长按是没有那个动画反馈的，不好。

**Comment by WindowsMEMZ** [comment]
> > ## 2月2日新增
> > 
> > * [x]   支持一键三连
> > * [ ]   支持识别动态中的链接并用Safari打开
> > * [ ]   动态图片/视频封面支持保存
> > * [ ]   新增点踩功能
> > * [ ]   支持管理收藏/稍后再看
> > * [ ]   支持创建/删除收藏夹
> > * [ ]   支持登录多个账号
> > * [ ]   私信支持图片上传
> > * [ ]   视频支持私信分享
> > * [ ]   评论支持多行
> > * [x]   支持显示评论中的表情包
> > * [x]   把`以太网`改成`网络连接` _小问题_ ([更新英语翻译 #108](https://github.com/Darock-Studio/Darock-Bili/pull/108) )
> 
> “用Safari打开”不可能，watchOS哪来的Safari

没关系，可以跳转到db或pi

**Comment by ThreeManager785** [comment]
> > > ## 2月2日新增
> > > 
> > > * [x]    支持一键三连
> > > * [ ]    支持识别动态中的链接并用Safari打开
> > > * [ ]    动态图片/视频封面支持保存
> > > * [ ]    新增点踩功能
> > > * [ ]    支持管理收藏/稍后再看
> > > * [ ]    支持创建/删除收藏夹
> > > * [ ]    支持登录多个账号
> > > * [ ]    私信支持图片上传
> > > * [ ]    视频支持私信分享
> > > * [ ]    评论支持多行
> > > * [x]    支持显示评论中的表情包
> > > * [x]    把`以太网`改成`网络连接` _小问题_ ([更新英语翻译 #108](https://github.com/Darock-Studio/Darock-Bili/pull/108) )
> > 
> > 
> > “用Safari打开”不可能，watchOS哪来的Safari
> 
> 没关系，可以跳转到db或pi

我也这么想

**Comment by ThreeManager785** [comment]
很遗憾的告诉你，你这里面全都是功能性反馈，我无能为力（

**Comment by WindowsMEMZ** [comment]
> 很遗憾的告诉你，你这里面全都是功能性反馈，我无能为力（

多账号登录你可以试试（

**Comment by ThreeManager785** [comment]
> > 很遗憾的告诉你，你这里面全都是功能性反馈，我无能为力（
> 
> 多账号登录你可以试试（

收到

**Comment by ThreeManager785** [comment]
「支持登录多个账号」现已支持！

**Comment by WindowsMEMZ** [comment]
> 「支持登录多个账号」现已支持！

你得push上来然后开个pr啊（

**Comment by ThreeManager785** [comment]
已手动添加

**Comment by WindowsMEMZ** [comment]
> 已手动添加

？你在干什么，别直接往main上面推啊，pr都不开，那么大个红字告诉你会绕过分支保护

**Comment by ThreeManager785** [comment]
对不起，不过clone了能跑
下次注意

**Comment by WindowsMEMZ** [comment]
找到[按钮按下的触发器](https://developer.apple.com/documentation/swiftui/buttonstyleconfiguration/ispressed)了，一键三连功能有救了！

**Comment by ThreeManager785** [comment]
草

**Comment by Linecom-lik** [comment]
# 2月9日新增 - 除夕快乐

- [ ] 增加拉黑用户功能
- [ ] 增加断点续播功能
- [ ] 增加熄屏暂停功能
- [ ] 稍后再看支持管理
- [ ] 支持显示粉丝勋章和成就勋章
- [ ] 用户页显示ip属地
- [ ] 用户页展示学校信息
- [ ] 用户页展示UID
- [ ] 用户视频支持按合集、列表显示
- [ ] 支持搜索单个用户的视频、动态
- [ ] 支持生成bilibili二维码名片
- [ ] 支持查看其他用户的关注列表
- [ ] 支持查看其他用户的粉丝列表
- [ ] 支持在用户页展示用户直播间入口

**Comment by Groupguanfang** [comment]
吃瓜👀直接往main推了，草
你们这是放了多少buff😂

**Comment by WindowsMEMZ** [comment]
> # 2月9日新增 - 除夕快乐
> * [ ]  增加拉黑用户功能
> * [ ]  增加断点续播功能
> * [ ]  增加熄屏暂停功能
> * [ ]  稍后再看支持管理
> * [ ]  支持显示粉丝勋章和成就勋章
> * [ ]  用户页显示ip属地
> * [ ]  用户页展示学校信息
> * [ ]  用户页展示UID
> * [ ]  用户视频支持按合集、列表显示
> * [ ]  支持搜索单个用户的视频、动态
> * [ ]  支持生成bilibili二维码名片
> * [ ]  支持查看其他用户的关注列表
> * [ ]  支持查看其他用户的粉丝列表
> * [ ]  支持在用户页展示用户直播间入口

哥们你先别提了，这么多加起来你看看，**75tasks**，再这样几天一大堆，喵哩似了这个Issue都还得在这啊😭。你先等等，等我把这里修完你再接着提，现在好好用就是了😇

**Comment by Groupguanfang** [comment]
太难绷了，75 tasks，我第一次见到有这么多的😂离谱

**Comment by WindowsMEMZ** [comment]
> 太难绷了，75 tasks，我第一次见到有这么多的😂离谱

主要是*tm*过两天就来一堆，这谁顶得住啊😭

**Comment by Groupguanfang** [comment]
> > 太难绷了，75 tasks，我第一次见到有这么多的😂离谱
> 
> 主要是_tm_过两天就来一堆，这谁顶得住啊😭

这些天过年就别干了吧，哈哈哈哈哈哈哈哈哈

tasks数量比star数量多系列，真的少见😂

**Comment by Groupguanfang** [comment]
我靠，刚才才看到，main分支怎么断了，草

**Comment by WindowsMEMZ** [comment]
> 我靠，刚才才看到，main分支怎么断了，草
> 
> @ThreeManager785 你不会直接—-force强制推送了😂

wtf，逆天

**Comment by WindowsMEMZ** [comment]
> > 我靠，刚才才看到，main分支怎么断了，草
> > @ThreeManager785 你不会直接—-force强制推送了😂
> 
> wtf，逆天

没有，我main不允许force，他是上传文件弄上去的，我直接改分支保护，不允许绕过了😇

**Comment by Groupguanfang** [comment]
> > > 我靠，刚才才看到，main分支怎么断了，草
> > > @ThreeManager785 你不会直接—-force强制推送了😂
> > 
> > 
> > wtf，逆天
> 
> 没有，我main不允许force，他是上传文件弄上去的，我直接改分支保护，不允许绕过了😇

还好，有分支保护，草

怎么直接上传文件啊😂这招难防啊

**Comment by WindowsMEMZ** [comment]
> > > > 我靠，刚才才看到，main分支怎么断了，草
> > > > @ThreeManager785 你不会直接—-force强制推送了😂
> > > 
> > > 
> > > wtf，逆天
> > 
> > 
> > 没有，我main不允许force，他是上传文件弄上去的，我直接改分支保护，不允许绕过了😇
> 
> 还好，有分支保护，草
> 
> 怎么直接上传文件啊😂这招难防啊

分支保护规则再多都抵不住勾一个Bypass，直接不允许Bypass完事🤗

**Comment by WindowsMEMZ** [comment]
> 支持发表文字动态

已有，不加图片即可

**Comment by WindowsMEMZ** [comment]
打勾的是目前不考虑/做不了的功能，我就不一一回复原因了

**Comment by Linecom-lik** [comment]
> > # 2月9日新增 - 除夕快乐
> > 
> > * [ ]   增加拉黑用户功能
> > * [ ]   增加断点续播功能
> > * [ ]   增加熄屏暂停功能
> > * [ ]   稍后再看支持管理
> > * [ ]   支持显示粉丝勋章和成就勋章
> > * [ ]   用户页显示ip属地
> > * [ ]   用户页展示学校信息
> > * [ ]   用户页展示UID
> > * [ ]   用户视频支持按合集、列表显示
> > * [ ]   支持搜索单个用户的视频、动态
> > * [ ]   支持生成bilibili二维码名片
> > * [ ]   支持查看其他用户的关注列表
> > * [ ]   支持查看其他用户的粉丝列表
> > * [ ]   支持在用户页展示用户直播间入口
> 
> 哥们你先别提了，这么多加起来你看看，**75tasks**，再这样几天一大堆，喵哩似了这个Issue都还得在这啊😭。你先等等，等我把这里修完你再接着提，现在好好用就是了😇

汗流浃背了吧（

**Comment by Groupguanfang** [comment]
牢弟，这么鞭尸😂

**Comment by ThreeManager785** [comment]
> 我靠，刚才才看到，main分支怎么断了，草
> 
> @ThreeManager785 你不会直接—-force强制推送了😂

对不起———

**Comment by ThreeManager785** [comment]
> > 我靠，刚才才看到，main分支怎么断了，草
> > @ThreeManager785 你不会直接—-force强制推送了😂
> 
> 对不起———

我也不知道，我就直接在main里Upload Files了（

**Comment by ThreeManager785** [comment]
睡眠提醒我觉得可以

**Comment by WindowsMEMZ** [comment]
> 睡眠提醒我觉得可以

那你来

**Comment by WindowsMEMZ** [comment]
All issues here have split, closing this issue
